version: '3'
services:
  web:
    restart: always
    build: ./web
    # volumes:
      # - $PWD/:/home/flask/web
    ports:
      - "80:5000"
  # nginx:
  #   restart: always
  #   build: ./nginx
  #   volumes:
  #     - $PWD/volume/html/:/usr/share/nginx/html
  #     - $PWD/volume/conf/nginx.conf:/etc/nginx/nginx.conf
  #     - $PWD/volume/logs:/var/log/nginx
  #     - $PWD/volume/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  #   ports:
  #     - "8080:80"