version: '3'
services:
  web:
    restart: always
    build: ./web
    volumes:
      - $PWD/web:/home/flask/web
    ports:
      - "80:5000"
  nginx:
    restart: always
    build: ./nginx
    volumes:
      - $PWD/nginx/volume/html/:/usr/share/nginx/html
      - $PWD/nginx/volume/conf/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/nginx/volume/logs:/var/log/nginx
      - $PWD/nginx/volume/conf.d/default.conf:/etc/nginx/config.d/default.conf
    ports:
      - "8080:80"